#version: '3.8'
#
#services:
#  db:
#    image: postgres:13.7-alpine
#    volumes:
#      - /var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=later
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#  web:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - DB_NAME=later
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - DB_HOST=db
#      - DB_PORT=5432

version: '3.8'
services:
  gateway:
    build: gateway
    container_name: gatewayShareit_container
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    container_name: serverShareit_container
    ports:
      - "9090:9090"
    depends_on:
    - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=postgres
#      - DB_NAME=shareit
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=postgres
#      - DB_HOST=db
#      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: postgres_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres